version: 2

# use a bit more modern tools to build the docs
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# indicate where sphinx conf is
sphinx:
   configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
