version: 2

# use a bit more modern tools to build the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# indicate where sphinx conf is
sphinx:
   configuration: docs/conf.py

# install the `dev` requirements
python:
  install:
    - requirements: requirements.txt
