# a more complete example of the linters which includes testing.
name: Lint and Test

on: [push, pull_request]

# the defined jobs
jobs:
  # the job build configuration and steps
  build:
    # we use ubuntu latest for this, which normally is the most recent LTS version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # check against the package supported versions
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python version ${{ matrix.python-version }}...
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Installing dependencies...
        # install the dependencies along with a set of required packages; if requirements is present
        # then, we install that as well.
        run: |
          python -m pip install -U pip
          pip install flake8 flake8-black pytest pylint pre-commit
          if [ -f requirements.txt ]; then pip install -r ./requirements.txt; fi
          sudo snap install shfmt
      # Python linting phase
      - name: Running pre-commit hooks...
        uses: pre-commit/action@v3.0.0
      # Shell linting phase
      - name: Running shell check...
        uses: ludeeus/action-shellcheck@master
      - name: Perform testing with pytest
        run: |
          pytest
        env:
          LIBRARIES_API_KEY: ${{ secrets.LIBRARIES_API_KEY }}
